experiment:
  experiment_id: cifar10_cnn
  wandb_project: CIFAR10-CNN-Optimizers
  task_type: image_classification
  dataset_name: cifar10
  model_name: airbench_cnn
  num_classes: 10
  image_size: 32
  total_training_steps: 720
  seeds: 50
batch_size: 500
grad_acc: 1
parameter_routing:
  conv_weights: muon
  normalization_and_biases: sgd
optimizers:
  adam:
    optimizer: adam
    lr: 0.001
    weight_decay: 0.001
  sgd:
    optimizer: sgd
    lr: 0.001
    momentum: 0.9
    nesterov: true
    weight_decay: 0.001
  muon:
    optimizer: muon
    lr: 0.02
    momentum: 0.9665
    momentum_type: nesterov
    weight_decay: 0.0001
    solver: quintic_theoretical
    steps_q: 7
  muon_sam:
    optimizer: muon_sam
    lr: 0.02
    momentum: 0.9665
    weight_decay: 0.0001
    rho: 0.0015
    rho_vector: 0.01
  atlas:
    optimizer: atlas
    lr: 0.02
    momentum: 0.9665
    weight_decay: 0.0001
    rho: 0.0015
    rho_vector: 0.01
  atlas_raw:
    optimizer: atlas_raw
    lr: 0.02
    momentum: 0.9665
    weight_decay: 0.0001
    rho: 0.0015
    rho_vector: 0.01
  atlas_random:
    optimizer: atlas_random
    lr: 0.02
    momentum: 0.9665
    weight_decay: 0.0001
    rho: 0.0015
    rho_vector: 0.01
