"""Fine-tuning curves of the 11 optimizers (v2 models): training loss and validation accuracy, 2 models x 4 datasets, as pgfplots/TikZ grids.

* Training loss: the curves SAVED by the v2 forgetting run (forgetting_results/<model>_s<seed>/<opt>_<dataset>.json) at the
  fine-tuning learning rate 1.78e-4 (a point of the v2 grid), mean over the 3 pretraining seeds, 64 steps.
* Validation accuracy (+ validation loss): next-token accuracy (%) on the held-out part of the new-task data (1,024 sequences x 512 tokens), measured
  every 8 steps by tools/ft_worker.py, which re-runs the identical recipe. Mean over 3 seeds.
All numbers are written to CSV; the .tex files only read them. Nothing outside this folder is modified.

  python tools/make_ft_figures.py
"""
import csv, json, os, shutil, statistics as st

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.join(REPO, "paper_ft_curves")   # output package (LaTeX + CSV); raw/ holds the re-run results of tools/ft_worker.py
os.makedirs(ROOT, exist_ok=True)
os.chdir(ROOT)
V2 = REPO
SEEDS = [42, 43, 44]
LRKEY = "0.000178"
DS = ["codeparrot", "stackmathqa", "musicpile", "tulu3"]
MODELS = {"nanogpt": "nanoGPT", "pythia70m": "Pythia-70M"}
NAMES = {"adam": "AdamW", "sgd": "SGD", "muon": "Muon", "sam": "SAM", "fsam": "FSAM", "muon_sam": "SpecSAM-Muon", "fsam_ortho_muon": "FP-SOMA",
         "fsam_ortho_muon_stale_momentum": "SOMA", "randsam_muon": "RandSAM-Muon", "soma_prens5": "SOMA-PreNS5", "op_soma_postns5": "OP-SOMA-PostNS5"}
STYLE = {"adam": ("000000", "solid"), "sgd": ("7F7F7F", "solid"), "muon": ("0072B2", "solid"), "sam": ("E69F00", "solid"), "fsam": ("E69F00", "densely dashed"),
         "muon_sam": ("56B4E9", "densely dashed"), "fsam_ortho_muon": ("009E73", "solid"), "fsam_ortho_muon_stale_momentum": ("CC79A7", "solid"),
         "randsam_muon": ("D55E00", "densely dashed"), "soma_prens5": ("6A3D9A", "solid"), "op_soma_postns5": ("8C564B", "densely dashed")}
key = lambda o: "ft-" + o.replace("_", "-")
sd = lambda xs: st.stdev(xs) if len(xs) > 1 else 0.0


def write_csv(path, header, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.writer(f); w.writerow(header); w.writerows(rows)


def main():
    for d in ("data", "plots", "common"):
        shutil.rmtree(d, ignore_errors=True)
    checks = []
    for m in MODELS:
        for o in NAMES:
            raw = [json.load(open(f"raw/{m}_{o}_s{s}.json")) for s in SEEDS]
            for ds in DS:
                tr = [json.load(open(f"{V2}/forgetting_results/{m}_s{s}/{o}_{ds}.json"))["train_loss_curves"][LRKEY] for s in SEEDS]
                write_csv(f"data/{m}/{o}_{ds}_train.csv", ["step", "train_loss", "train_loss_sd"],
                          [[i + 1, f"{st.mean(c[i] for c in tr):.5f}", f"{sd([c[i] for c in tr]):.5f}"] for i in range(len(tr[0]))])
                steps = raw[0]["results"][ds]["val_steps"]
                write_csv(f"data/{m}/{o}_{ds}_val.csv", ["step", "val_loss", "val_loss_sd", "val_acc", "val_acc_sd"],
                          [[s_, *[f"{x:.5f}" for x in (st.mean(r["results"][ds]["val_loss"][k] for r in raw), sd([r["results"][ds]["val_loss"][k] for r in raw]),
                                                        st.mean(r["results"][ds]["val_acc"][k] for r in raw), sd([r["results"][ds]["val_acc"][k] for r in raw]))]]
                           for k, s_ in enumerate(steps)])
                for r, s in zip(raw, SEEDS):
                    c = r["results"][ds]
                    checks.append([m, o, ds, s, f"{c['check_train_curve_max_abs_diff']:.4g}", f"{c['check_val_base_diff']:.4g}", f"{c['check_val_final_diff']:.4g}"])
    write_csv("data/reproduction_check.csv", ["model", "optimizer", "dataset", "seed", "train_curve_max_abs_diff_vs_v2", "val_loss_step0_diff_vs_v2", "val_loss_step64_diff_vs_v2"], checks)
    # ---------- preamble ----------
    pre = ["% AUTO-GENERATED by tools/make_ft_figures.py", r"\usepackage{pgfplots}", r"\usepgfplotslibrary{groupplots}", r"\pgfplotsset{compat=1.17}",
           r"\providecommand{\ftroot}{paper_ft_curves}  % folder that contains data/",
           r"\providecommand{\fitwidth}[1]{\resizebox{\ifdim\width>\textwidth\textwidth\else\width\fi}{!}{#1}}  % shrink to the text width only if wider", ""]
    for o, (hexcol, dash) in STYLE.items():
        pre += [r"\definecolor{c%s}{HTML}{%s}" % (key(o), hexcol), r"\pgfplotsset{%s/.style={color=c%s, %s, line width=0.7pt, mark=none}}" % (key(o), key(o), dash)]
    pre.append(r"""
\pgfplotsset{
  ft grid axis/.style={width=0.225\textwidth, height=0.19\textwidth, grid=major, grid style={gray!25}, xmin=0, xmax=64,
    tick label style={font=\tiny}, label style={font=\scriptsize}, title style={font=\scriptsize, yshift=-2pt},
    ylabel style={align=center}, scaled y ticks=false},
}
""")
    os.makedirs("common"); open("common/preamble.tex", "w").write("\n".join(pre))
    # ---------- two grids ----------
    os.makedirs("plots")
    specs = {"train_loss": ("train", "train_loss", "Fine-tuning\\\\train loss", "Fine-tuning training loss", "Fine-tuning step"),
             "val_acc": ("val", "val_acc", "Fine-tuning\\\\val.\\ accuracy (\\%)", "Fine-tuning validation accuracy", "Fine-tuning step")}
    for name, (suffix, col, ylab, _, xlab) in specs.items():
        g = ["% AUTO-GENERATED: rows = models, columns = fine-tuning datasets, lines = optimizers", r"\begin{tikzpicture}",
             r"\begin{groupplot}[ft grid axis, group style={group size=4 by 2, horizontal sep=1.15cm, vertical sep=1.5cm, xlabels at=edge bottom, xticklabels at=edge bottom}]"]
        for r, (m, short) in enumerate(MODELS.items()):
            for c, ds in enumerate(DS):
                opts = ["xlabel={%s}" % xlab] if r == 1 else []
                if r == 0: opts.append("title={%s}" % ds)
                if c == 0: opts.append("ylabel={%s\\\\%s}" % (short, ylab.replace("\\\\", "\\\\")))
                first = r == 0 and c == 0
                if first: opts += ["legend to name=ftlegend%s" % name.replace("_", ""), "legend columns=6", r"legend style={font=\scriptsize, draw=none}"]
                g.append(r"\nextgroupplot[" + ", ".join(opts) + "]")
                for o in NAMES:
                    extra = ", mark=*, mark size=0.9pt" if suffix == "val" else ""
                    g.append(r"\addplot[%s%s] table[col sep=comma, x=step, y=%s]{\ftroot/data/%s/%s_%s_%s.csv};" % (key(o), extra, col, m, o, ds, suffix))
                    if first: g.append(r"\addlegendentry{%s}" % NAMES[o])
        g += [r"\end{groupplot}", r"\end{tikzpicture}", ""]
        open(f"plots/grid_{name}.tex", "w").write("\n".join(g))
    cap = {"train_loss": "Fine-tuning training loss (AdamW, learning rate $1.78\\times10^{-4}$, 64 steps) of the models pretrained with each optimizer; mean over 3 pretraining seeds. "
                         "Rows: nanoGPT (GPT-2 small) and Pythia-70M. Columns: fine-tuning dataset.",
           "val_acc": "Held-out next-token accuracy (\\%) during fine-tuning (AdamW, learning rate $1.78\\times10^{-4}$) of the models pretrained with each optimizer, measured every 8 steps; "
                      "mean over 3 pretraining seeds. Rows: nanoGPT (GPT-2 small) and Pythia-70M. Columns: fine-tuning dataset."}
    for name in specs:
        open(f"figure_ft_{name}.tex", "w").write(
            "%% AUTO-GENERATED\n\\begin{figure*}[t]\n  \\centering\n  \\fitwidth{\\input{\\ftroot/plots/grid_%s.tex}}\n\n  \\vspace{3pt}\n  \\ref{ftlegend%s}\n"
            "  \\caption{%s}\n  \\label{fig:ft-%s}\n\\end{figure*}\n" % (name, name.replace("_", ""), cap[name], name.replace("_", "-")))
    open("main.tex", "w").write(r"""% Complete example: compile with pdfLaTeX; main.tex sits next to common/, data/, plots/.
\documentclass[10pt,twocolumn]{article}
\usepackage[margin=0.75in,columnsep=0.25in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{amsmath,amssymb}
\newcommand{\ftroot}{.}
\input{\ftroot/common/preamble.tex}
\title{Fine-tuning curves}\author{}\date{}
\begin{document}
\maketitle
\input{\ftroot/figure_ft_train_loss.tex}
\input{\ftroot/figure_ft_val_acc.tex}
\end{document}
""")
    open("README.md", "w").write("""# paper_ft_curves: fine-tuning curves (training loss, validation accuracy) of the 11 v2 optimizers

* `figure_ft_train_loss.tex`, `figure_ft_val_acc.tex`: 2 models x 4 datasets grids (each a full-width figure*, shared legend).
* `plots/grid_*.tex`: the TikZ grids. `data/<model>/<opt>_<dataset>_{train,val}.csv`: every plotted number (mean and sd over 3 seeds).
* Training loss = curves saved by the v2 forgetting run (LR 1.78e-4); validation accuracy = re-run of the same recipe with evaluation every 8 steps
  (`tools/ft_worker.py`, raw output in `raw/`). `data/reproduction_check.csv` compares the re-run with the saved v2 results.
Overleaf: upload the folder, set `\\newcommand{\\ftroot}{paper_ft_curves}` + `\\input{\\ftroot/common/preamble.tex}`, then `\\input{\\ftroot/figure_ft_val_acc.tex}`.
""")
    mx = max(float(c[4]) for c in checks), max(float(c[6]) for c in checks), max(float(c[5]) for c in checks)
    print("reproduction check over", len(checks), "runs: max train-curve diff %.3g | max val-loss(step0) diff %.3g | max val-loss(step64) diff %.3g" % (mx[0], mx[2], mx[1]))


if __name__ == "__main__":
    main()
