"""Training curves of the 11 optimizers on the 3 models (normal experiments, not PTQ / forgetting): 9 pgfplots/TikZ plots.

Per model: (1) training loss, (2) validation accuracy, (3) validation perplexity, per epoch, mean over the 3 pretraining seeds.
Source: logs/{nanogpt,pythia70m,cifar10}_v2_logs.csv (written by main_experiment.py).
Notes: language models: accuracy = next-token accuracy (%), perplexity = exp(validation loss); CIFAR-10: accuracy = top-1 accuracy (%) on the 5,000-image validation set held out from the training set (not the test set),
"perplexity" = exp(validation cross-entropy), computed here per seed (the CNN log has no perplexity column).
Validation metrics of all models use the first 50 batches of a fixed validation stream (LM: ~0.41M tokens), identical for every optimizer.
Training loss of the single-gradient-pass methods (SOMA, SOMA-PreNS5, OP-SOMA-PostNS5, RandSAM-Muon) is measured at the perturbed weights.

  python tools/make_curves.py  ->  data/, plots/, figure_curves.tex, main.tex, README.md
"""
import csv, math, os, shutil, statistics as st
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(REPO, "paper_curves")      # output package (LaTeX + CSV)
os.makedirs(PKG, exist_ok=True)
os.chdir(PKG)
SRC = os.path.join(REPO, "logs")
SEEDS = {"42", "43", "44"}
MODELS = {"nanogpt": ("nanoGPT (GPT-2 small)", "nanogpt_v2"), "pythia70m": ("Pythia-70M", "pythia70m_v2"), "cifar10": ("airbench CNN, CIFAR-10", "cifar10_v2")}
NAMES = {"adam": "AdamW", "sgd": "SGD", "muon": "Muon", "sam": "SAM", "fsam": "FSAM", "muon_sam": "SpecSAM-Muon", "fsam_ortho_muon": "FP-SOMA",
         "fsam_ortho_muon_stale_momentum": "SOMA", "randsam_muon": "RandSAM-Muon", "soma_prens5": "SOMA-PreNS5", "op_soma_postns5": "OP-SOMA-PostNS5"}
STYLE = {"adam": ("000000", "solid"), "sgd": ("7F7F7F", "solid"), "muon": ("0072B2", "solid"), "sam": ("E69F00", "solid"), "fsam": ("E69F00", "densely dashed"),
         "muon_sam": ("56B4E9", "densely dashed"), "fsam_ortho_muon": ("009E73", "solid"), "fsam_ortho_muon_stale_momentum": ("CC79A7", "solid"),
         "randsam_muon": ("D55E00", "densely dashed"), "soma_prens5": ("6A3D9A", "solid"), "op_soma_postns5": ("8C564B", "densely dashed")}
METRICS = {"train_loss": ("Training loss", "train_loss"), "val_acc": ("Validation accuracy (\\%)", "val_acc"), "val_ppl": ("Validation perplexity", "val_ppl")}
key = lambda o: "cv-" + o.replace("_", "-")
sd = lambda xs: st.stdev(xs) if len(xs) > 1 else 0.0


def load(cid, lm):
    per = {}
    for r in csv.DictReader(open(f"{SRC}/{cid}_logs.csv")):
        if r["seed"] not in SEEDS or r["optimizer"] not in NAMES:
            continue
        vl = float(r["val_loss"])
        per.setdefault((r["optimizer"], int(r["epoch"])), []).append(
            (float(r["train_loss"]), float(r["val_accuracy"]), float(r["val_perplexity"]) if lm else math.exp(vl)))
    return per


def main():
    for d in ("data", "plots", "common"):
        shutil.rmtree(d, ignore_errors=True)
    os.makedirs("data"); os.makedirs("plots"); os.makedirs("common")
    ranges = {}
    for m, (title, cid) in MODELS.items():
        per = load(cid, m != "cifar10")
        epochs = sorted({e for (_, e) in per})
        for o in NAMES:
            assert all(len(per[(o, e)]) == 3 for e in epochs), (m, o)
            os.makedirs(f"data/{m}", exist_ok=True)
            with open(f"data/{m}/{o}.csv", "w", newline="") as f:
                w = csv.writer(f); w.writerow(["epoch", "train_loss", "train_loss_sd", "val_acc", "val_acc_sd", "val_ppl", "val_ppl_sd"])
                for e in epochs:
                    v = per[(o, e)]
                    w.writerow([e] + [f"{x:.5f}" for i in range(3) for x in (st.mean(t[i] for t in v), sd([t[i] for t in v]))])
        ranges[m] = len(epochs)
    pre = ["% AUTO-GENERATED by tools/make_curves.py", r"\usepackage{pgfplots}", r"\usepgfplotslibrary{groupplots}", r"\pgfplotsset{compat=1.17}",
           r"\providecommand{\curvesroot}{paper_curves}  % folder that contains data/",
           r"\providecommand{\fitwidth}[1]{\resizebox{\ifdim\width>\textwidth\textwidth\else\width\fi}{!}{#1}}  % shrink to the text width only if wider", ""]
    for o, (hexcol, dash) in STYLE.items():
        pre += [r"\definecolor{c%s}{HTML}{%s}" % (key(o), hexcol),
                r"\pgfplotsset{%s/.style={color=c%s, %s, line width=0.8pt, mark=none}}" % (key(o), key(o), dash)]
    pre.append(r"""
\pgfplotsset{
  curve axis/.style={width=\columnwidth, height=0.72\columnwidth, grid=major, grid style={gray!25}, xlabel={Epoch},
    tick label style={font=\scriptsize}, label style={font=\footnotesize}, title style={font=\footnotesize},
    legend style={font=\tiny, draw=none, fill=white, fill opacity=0.8, text opacity=1}, scaled y ticks=false},
  grid curve axis/.style={width=0.31\textwidth, height=0.25\textwidth, grid=major, grid style={gray!25},
    tick label style={font=\tiny}, label style={font=\scriptsize}, title style={font=\scriptsize, yshift=-2pt}, scaled y ticks=false},
}
""")
    open("common/preamble.tex", "w").write("\n".join(pre))
    # ---- 9 single plots ----
    for m, (title, cid) in MODELS.items():
        for mk, (ylabel, col) in METRICS.items():
            t = ["% AUTO-GENERATED", r"\begin{tikzpicture}", r"\begin{axis}[curve axis, title={%s}, ylabel={%s}, xmin=1, xmax=%d," % (title, ylabel, ranges[m]),
                 "  legend pos=%s]" % ("south east" if mk == "val_acc" else "north east")]
            for o in NAMES:
                t += [r"\addplot[%s] table[col sep=comma, x=epoch, y=%s]{\curvesroot/data/%s/%s.csv};" % (key(o), col, m, o), r"\addlegendentry{%s}" % NAMES[o]]
            t += [r"\end{axis}", r"\end{tikzpicture}", ""]
            open(f"plots/{m}_{mk}.tex", "w").write("\n".join(t))
    # ---- 3x3 grid (rows = models, columns = metrics), one shared legend ----
    g = ["% AUTO-GENERATED: rows = models, columns = training loss / validation accuracy / validation perplexity", r"\begin{tikzpicture}",
         r"\begin{groupplot}[grid curve axis, group style={group size=3 by 3, horizontal sep=1.45cm, vertical sep=1.35cm}]"]
    for r, (m, (title, cid)) in enumerate(MODELS.items()):
        for c, (mk, (ylabel, col)) in enumerate(METRICS.items()):
            opts = ["xmin=1", "xmax=%d" % ranges[m]]
            if r == 0: opts.append("title={%s}" % ylabel)                       # column titles = metric names
            if c == 0: opts.append("ylabel={%s}" % title.split(" (")[0].split(",")[0])   # row labels = model names
            if r == 2: opts.append("xlabel={Epoch}")
            first = r == 0 and c == 0
            if first: opts += ["legend to name=curveslegend", "legend columns=6", r"legend style={font=\scriptsize, draw=none}"]
            g.append(r"\nextgroupplot[" + ", ".join(opts) + "]")
            for o in NAMES:
                g.append(r"\addplot[%s] table[col sep=comma, x=epoch, y=%s]{\curvesroot/data/%s/%s.csv};" % (key(o), col, m, o))
                if first: g.append(r"\addlegendentry{%s}" % NAMES[o])
    g += [r"\end{groupplot}", r"\end{tikzpicture}", ""]
    open("plots/grid_all.tex", "w").write("\n".join(g))
    open("figure_curves.tex", "w").write(
        "% AUTO-GENERATED\n\\begin{figure*}[t]\n  \\centering\n  \\fitwidth{\\input{\\curvesroot/plots/grid_all.tex}}\n\n  \\vspace{3pt}\n  \\ref{curveslegend}\n"
        "  \\caption{Pretraining curves of the eleven optimizers (mean over 3 seeds) on nanoGPT, Pythia-70M and the CIFAR-10 CNN: training loss, validation accuracy "
        "and validation perplexity per epoch. For CIFAR-10 the perplexity is $\\exp$ of the validation cross-entropy. Training loss of single-pass methods "
        "(SOMA, SOMA-PreNS5, OP-SOMA-PostNS5, RandSAM-Muon) is measured at the perturbed weights.}\n  \\label{fig:curves}\n\\end{figure*}\n")
    open("main.tex", "w").write(r"""% Complete example: compile with pdfLaTeX; main.tex sits next to common/, data/, plots/.
\documentclass[10pt,twocolumn]{article}
\usepackage[margin=0.75in,columnsep=0.25in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{amsmath,amssymb}
\usepackage{hyperref}
\newcommand{\curvesroot}{.}
\input{\curvesroot/common/preamble.tex}
\title{Training Curves of Eleven Optimizers}
\author{}\date{}
\begin{document}
\maketitle
\section{Training curves}
Figure~\ref{fig:curves} shows the full 3$\times$3 grid. Each panel is also available as a single-column plot
(\texttt{plots/<model>\_<metric>.tex}), e.g. Figure~\ref{fig:single}.

\input{\curvesroot/figure_curves.tex}

\begin{figure}[t]
  \centering
  \input{\curvesroot/plots/nanogpt_val_ppl.tex}
  \caption{Single plot example: validation perplexity of nanoGPT.}
  \label{fig:single}
\end{figure}
\end{document}
""")
    open("README.md", "w").write("""# paper_curves: training curves of the 11 optimizers on 3 models (normal experiments)

* `plots/<model>_<metric>.tex`: 9 single-column plots (models: nanogpt, pythia70m, cifar10; metrics: train_loss, val_acc, val_ppl).
* `plots/grid_all.tex` + `figure_curves.tex`: all 9 as one 3x3 full-width figure with a shared legend.
* `data/<model>/<optimizer>.csv`: per-epoch mean and sd over 3 seeds (the .tex files only read these). `common/preamble.tex`: styles.
* Source: logs/*_v2_logs.csv. Regenerate: `python tools/make_curves.py`.
Overleaf: upload this folder; preamble `\\newcommand{\\curvesroot}{paper_curves}` + `\\input{\\curvesroot/common/preamble.tex}`; body `\\input{\\curvesroot/figure_curves.tex}`
or `\\input{\\curvesroot/plots/<model>_<metric>.tex}` inside a `figure`.
""")
    print("epochs per model:", ranges)


if __name__ == "__main__":
    main()
