"""Export the fine-tuning TRAINING-LOSS curves of the catastrophic-forgetting experiments as one pgfplots/TikZ grid.

A 2 x 4 grid: one row per model (nanoGPT, Pythia-70M), one column per fine-tuning dataset, and all 9 optimizers as lines in
every panel. Numbers live in CSV files (read by LaTeX at compile time); the .tex files contain no data.

  python tools/make_tikz.py [--curve-lr 0.000224]

  paper_figures/common/preamble.tex                     packages + styles (one line style per optimizer)
  paper_figures/data/<model>/<opt>_<dataset>.csv        step, train_loss, lr   (64 fine-tuning steps; from forgetting_results/<model>/*.json)
  paper_figures/train_loss_grid.tex                     the 2 x 4 tikzpicture
  paper_figures/figure_train_loss.tex                   figure* wrapper (shared legend + caption)
"""
import os
import csv
import json
import shutil
import argparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "paper_figures")
SRC = os.path.join(ROOT, "forgetting_results")
DATASETS = ["codeparrot", "stackmathqa", "musicpile", "tulu3"]
MODELS = {"nanogpt": "nanoGPT", "pythia70m": "Pythia-70M"}
# internal name -> paper name
NAMES = {"adam": "AdamW", "sgd": "SGD", "muon": "Muon", "sam": "SAM", "fsam": "FSAM", "muon_sam": "SpecSAM-Muon",
         "fsam_ortho_muon": "FP-SOMA", "fsam_ortho_muon_stale_momentum": "SOMA", "randsam_muon": "RandSAM-Muon"}
STYLES = {  # internal name -> (colour hex, dash)
    "adam": ("000000", "solid"), "sgd": ("7F7F7F", "solid"), "muon": ("0072B2", "solid"), "sam": ("E69F00", "solid"),
    "fsam": ("E69F00", "densely dashed"), "muon_sam": ("56B4E9", "densely dashed"), "fsam_ortho_muon": ("009E73", "solid"),
    "fsam_ortho_muon_stale_momentum": ("CC79A7", "solid"), "randsam_muon": ("D55E00", "densely dashed")}


# Panel geometry (fractions of \textwidth). Total width = 4*PANEL_W + 3*HSEP + ~1.1cm of y-label/tick space; keep it below 1.0\textwidth.
PANEL_W, PANEL_H, HSEP, VSEP = 0.185, 0.17, "0.8cm", "1.5cm"


def sty(o):
    return "os-" + o.replace("_", "-")


def preamble():
    out = ["% AUTO-GENERATED by tools/make_tikz.py", r"\usepackage{pgfplots}", r"\usepgfplotslibrary{groupplots}",
           r"\pgfplotsset{compat=1.17}", r"\providecommand{\figroot}{paper_figures}  % folder that contains data/", ""]
    for o, (hexcol, dash) in STYLES.items():
        out.append(r"\definecolor{c-%s}{HTML}{%s}" % (o.replace("_", "-"), hexcol))
        out.append(r"\pgfplotsset{%s/.style={color=c-%s, %s, line width=0.7pt, mark=none}}" % (sty(o), o.replace("_", "-"), dash))
    out.append(r"""
\pgfplotsset{
  trainloss/.style={width=%.3f\textwidth, height=%.3f\textwidth, grid=major, grid style={gray!25}, xmin=1, xmax=64,
    tick label style={font=\tiny}, label style={font=\scriptsize}, title style={font=\scriptsize, yshift=-2pt},
    ylabel style={align=center}, scaled y ticks=false},
}
""" % (PANEL_W, PANEL_H))
    return "\n".join(out)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def grid_tex(present):
    lines = ["% AUTO-GENERATED by tools/make_tikz.py: rows = models, columns = datasets, lines = optimizers",
             r"\begin{tikzpicture}",
             r"\begin{groupplot}[trainloss, group style={group size=4 by 2, horizontal sep=" + HSEP + ", vertical sep=" + VSEP + ",",
             r"    xlabels at=edge bottom, xticklabels at=edge bottom}]"]
    for r, (model, short) in enumerate(MODELS.items()):
        for c, ds in enumerate(DATASETS):
            opts = []
            if c == 0:
                opts.append("ylabel={%s\\\\Fine-tuning train loss}" % short)
            if r == 0:
                opts.append("title={%s}" % ds)
            if r == len(MODELS) - 1:
                opts.append("xlabel={Fine-tuning step}")
            first = r == 0 and c == 0
            if first:
                opts += ["legend to name=trainlosslegend", "legend columns=5",
                         r"legend style={font=\scriptsize, draw=none, /tikz/every even column/.append style={column sep=6pt}}"]
            lines.append(r"\nextgroupplot[" + ", ".join(opts) + "]")
            for o in NAMES:
                if (model, o, ds) in present:
                    lines.append(r"\addplot[%s] table[col sep=comma, x=step, y=train_loss]{\figroot/data/%s/%s_%s.csv};" % (sty(o), model, o, ds))
                    if first:
                        lines.append(r"\addlegendentry{%s}" % NAMES[o])
    lines += [r"\end{groupplot}", r"\end{tikzpicture}", ""]
    return "\n".join(lines)


def figure_tex(lr):
    return ("% AUTO-GENERATED: \\input this in the body (needs common/preamble.tex in the preamble)\n"
            "\\begin{figure*}[t]\n  \\centering\n  \\input{\\figroot/train_loss_grid.tex}\n\n  \\vspace{2pt}\n  \\ref{trainlosslegend}\n"
            "  \\caption{Fine-tuning training loss (AdamW, learning rate $LRVALUE$) of the models pretrained with each optimizer. "
            "Rows: nanoGPT (GPT-2 small) and Pythia-70M. Columns: fine-tuning dataset.}\n  \\label{fig:trainloss}\n\\end{figure*}\n").replace("LRVALUE", "%g" % lr)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--curve-lr", type=float, default=0.000224, help="fine-tuning LR (a grid point) of the plotted curves")
    a = ap.parse_args()
    for sub in ("common", "data", *MODELS):   # this script owns these folders
        shutil.rmtree(os.path.join(OUT, sub), ignore_errors=True)
    for f in ("main.tex", "train_loss_grid.tex", "figure_train_loss.tex"):
        if os.path.exists(os.path.join(OUT, f)):
            os.remove(os.path.join(OUT, f))
    write(os.path.join(OUT, "common", "preamble.tex"), preamble())
    present = set()
    for model in MODELS:
        for o in NAMES:
            for ds in DATASETS:
                path = os.path.join(SRC, model, f"{o}_{ds}.json")
                if not os.path.exists(path):
                    continue
                curves = json.load(open(path))["train_loss_curves"]
                k = [k for k in curves if abs(float(k) - a.curve_lr) / a.curve_lr < 1e-6]
                if k:
                    os.makedirs(os.path.join(OUT, "data", model), exist_ok=True)
                    with open(os.path.join(OUT, "data", model, f"{o}_{ds}.csv"), "w", newline="") as fh:
                        w = csv.writer(fh)
                        w.writerow(["step", "train_loss", "lr"])
                        w.writerows([[i + 1, y, a.curve_lr] for i, y in enumerate(curves[k[0]])])
                    present.add((model, o, ds))
    write(os.path.join(OUT, "train_loss_grid.tex"), grid_tex(present))
    write(os.path.join(OUT, "figure_train_loss.tex"), figure_tex(a.curve_lr))
    print(len(present), "curves;", len(MODELS) * len(DATASETS), "panels")


if __name__ == "__main__":
    main()
